name: Simple Test

'on':
  workflow_dispatch:
    inputs:
      timeout:
        type: string
        default: '60'

jobs:
  run-agent:
    name: Run Test
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - run: echo "Test with timeout"
